db.infracoes_ctb.insertMany([
  // LEVES - 3 Pontos - R$ 88,38
  { "artigo": "169", "descricao": "Dirigir sem atenção ou sem os cuidados indispensáveis à segurança.", "grau": "Leve", "pontos": 3, "valor": 88.38 },
  { "artigo": "177", "descricao": "Deixar de prestar socorro à vítima de acidente de trânsito quando solicitado pela autoridade e seus agentes.", "grau": "Leve", "pontos": 3, "valor": 88.38 },
  { "artigo": "181 I", "descricao": "Estacionar o veículo nas esquinas e a menos de cinco metros do bordo do alinhamento da via transversal.", "grau": "Leve", "pontos": 3, "valor": 88.38 },
  { "artigo": "181 II", "descricao": "Estacionar o veículo afastado da guia da calçada (meio-fio) de cinqüenta centímetros a um metro.", "grau": "Leve", "pontos": 3, "valor": 88.38 },
  { "artigo": "183", "descricao": "Parar o veículo sobre a faixa de pedestres na mudança de sinal luminoso.", "grau": "Leve", "pontos": 3, "valor": 88.38 },
  { "artigo": "205", "descricao": "Ultrapassar veículo em movimento que integre cortejo, préstito, desfile e formações militares, salvo com autorização.", "grau": "Leve", "pontos": 3, "valor": 88.38 },
  { "artigo": "224", "descricao": "Fazer uso do facho de luz alta dos faróis em vias providas de iluminação pública.", "grau": "Leve", "pontos": 3, "valor": 88.38 },
  { "artigo": "232", "descricao": "Conduzir veículo sem os documentos de porte obrigatório referidos neste Código.", "grau": "Leve", "pontos": 3, "valor": 88.38 },
  { "artigo": "236", "descricao": "Rebocar outro veículo com cabo flexível ou corda, salvo em casos de emergência.", "grau": "Leve", "pontos": 3, "valor": 88.38 },
  { "artigo": "241", "descricao": "Deixar de atualizar o cadastro de registro do veículo ou de habilitação do condutor.", "grau": "Leve", "pontos": 3, "valor": 88.38 },
  { "artigo": "254 I", "descricao": "É proibido ao pedestre permanecer ou andar nas pistas de rolamento, exceto para cruzá-las onde for permitido.", "grau": "Leve", "pontos": 0, "valor": 44.19 },
  { "artigo": "254 V", "descricao": "É proibido ao pedestre andar fora da faixa própria, passarela, passagem aérea ou subterrânea.", "grau": "Leve", "pontos": 0, "valor": 44.19 },

  // MÉDIAS - 4 Pontos - R$ 130,16
  { "artigo": "171", "descricao": "Usar o veículo para arremessar, sobre os pedestres ou veículos, água ou detritos.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "172", "descricao": "Atirar do veículo ou abandonar na via objetos ou substâncias.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "180", "descricao": "Ter seu veículo imobilizado na via por falta de combustível.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "181 III", "descricao": "Estacionar o veículo afastado da guia da calçada (meio-fio) a mais de um metro.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "181 IV", "descricao": "Estacionar o veículo em desacordo com as posições estabelecidas neste Código.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "181 VI", "descricao": "Estacionar o veículo junto ou sobre hidrantes de incêndio, registro de água ou tampas de poços de visita de galerias subterrâneas.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "181 X", "descricao": "Estacionar o veículo impedindo a movimentação de outro veículo.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "181 XIII", "descricao": "Estacionar o veículo onde houver sinalização horizontal delimitadora de ponto de embarque ou desembarque de passageiros de transporte coletivo.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "182 I", "descricao": "Parar o veículo nas esquinas e a menos de cinco metros do bordo do alinhamento da via transversal.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "182 IV", "descricao": "Parar o veículo em desacordo com as posições estabelecidas neste Código.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "182 VI", "descricao": "Parar o veículo no passeio ou sobre faixa destinada a pedestres, nas ilhas, refúgios, canteiros centrais e divisores de pista de rolamento e marcas de canalização.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "184", "descricao": "Transitar com o veículo na faixa ou pista da direita, regulamentada como de circulação exclusiva para determinado tipo de veículo, exceto para acesso a imóveis lindeiros ou conversões à direita.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "185 I", "descricao": "Quando o veículo estiver em movimento, deixar de conservá-lo na faixa a ele destinada pela sinalização de regulamentação, exceto em situações de emergência.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "185 II", "descricao": "Quando o veículo estiver em movimento, deixar de conservar nas faixas da direita os veículos lentos e de maior porte.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "201", "descricao": "Deixar de guardar a distância lateral de um metro e cinqüenta centímetros ao passar ou ultrapassar bicicleta.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "218 I", "descricao": "Transitar em velocidade superior à máxima permitida em até 20%.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "219", "descricao": "Transitar com o veículo em velocidade inferior à metade da velocidade máxima estabelecida para a via, retardando ou obstruindo o trânsito, a menos que as condições de tráfego e meteorológicas não o permitam, salvo se estiver na faixa da direita.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "221", "descricao": "Portar no veículo placas de identificação em desacordo com as especificações e modelos estabelecidos pelo CONTRAN.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "222", "descricao": "Deixar de manter ligado, nas situações de atendimento de emergência, o sistema de iluminação vermelha intermitente dos veículos de polícia, de socorro de incêndio e salvamento, de fiscalização de trânsito e das ambulâncias, ainda que parados.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "228", "descricao": "Usar no veículo equipamento com som em volume ou freqüência que não sejam autorizados pelo CONTRAN.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "235", "descricao": "Conduzir pessoas, animais ou carga nas partes externas do veículo, salvo nos casos devidamente autorizados.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "244 VI", "descricao": "Conduzir motocicleta, motoneta e ciclomotor rebocando outro veículo.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "244 VII", "descricao": "Conduzir motocicleta, motoneta e ciclomotor sem segurar o guidom com ambas as mãos, salvo eventualmente para indicação de manobras.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "245", "descricao": "Utilizar a via para depósito de mercadorias, materiais ou equipamentos, sem autorização do órgão ou entidade de trânsito com circunscrição sobre a via.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "249", "descricao": "Deixar de manter acesas, à noite, as luzes de posição, quando o veículo estiver parado para fins de embarque ou desembarque de passageiros e carga ou descarga de mercadorias.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "250 I a", "descricao": "Quando o veículo estiver em movimento: deixar de manter acesa a luz baixa durante a noite.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "250 I b", "descricao": "Quando o veículo estiver em movimento: deixar de manter acesa a luz baixa de dia, nos túneis providos de iluminação pública e nas rodovias.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "250 I c", "descricao": "Quando o veículo estiver em movimento: deixar de manter acesa a luz baixa de dia e de noite, tratando-se de veículo de transporte coletivo de passageiros, circulando em faixas ou pistas a eles destinadas.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "250 I d", "descricao": "Quando o veículo estiver em movimento: deixar de manter acesa a luz baixa de dia e de noite, tratando-se de ciclomotores.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "251", "descricao": "Utilizar as luzes do veículo: o pisca-alerta, exceto em imobilizações ou situações de emergência; baixa e alta de forma intermitente, exceto nas situações permitidas.", "grau": "Média", "pontos": 4, "valor": 130.16 },
  { "artigo": "255", "descricao": "Conduzir bicicleta em passeios onde não seja permitida a circulação desta, ou de forma agressiva.", "grau": "Média", "pontos": 0, "valor": 130.16 },
  
  // GRAVES - 5 Pontos - R$ 195,23
  { "artigo": "167", "descricao": "Deixar o condutor ou passageiro de usar o cinto de segurança.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "176 V", "descricao": "Deixar o condutor, envolvido em acidente com vítimas, de identificar-se ao policial e de lhe prestar informações necessárias à confecção do boletim de ocorrência.", "grau": "Grave", "pontos": 5, "valor": 976.15 },
  { "artigo": "181 V", "descricao": "Estacionar o veículo na pista de rolamento das estradas, das rodovias, das vias de trânsito rápido e das vias dotadas de acostamento.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "181 VIII", "descricao": "Estacionar o veículo no passeio ou sobre faixa destinada a pedestre, sobre ciclovia ou ciclofaixa, bem como nas ilhas, refúgios, ao lado ou sobre canteiros centrais, divisores de pista de rolamento, marcas de canalização, gramados ou jardins públicos.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "181 XI", "descricao": "Estacionar o veículo ao lado de outro veículo em fila dupla.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "181 XVII", "descricao": "Estacionar o veículo em desacordo com as condições regulamentadas especificamente pela sinalização (placa - Estacionamento Regulamentado).", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "181 XVIII", "descricao": "Estacionar o veículo em locais e horários proibidos especificamente pela sinalização (placa - Proibido Estacionar).", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "181 XIX", "descricao": "Estacionar o veículo em locais e horários de estacionamento e parada proibidos pela sinalização (placa - Proibido Parar e Estacionar).", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "182 V", "descricao": "Parar o veículo na pista de rolamento das estradas, das rodovias, das vias de trânsito rápido e das demais vias dotadas de acostamento.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "186 II", "descricao": "Transitar pela contramão de direção em vias com sinalização de regulamentação de sentido único de circulação.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "192", "descricao": "Deixar de guardar distância de segurança, lateral e frontal, entre o seu veículo e os demais, bem como em relação ao bordo da pista, considerando-se, no momento, a velocidade e as condições do local, da circulação, do veículo e as condições climáticas.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "197", "descricao": "Deixar de deslocar, com antecedência, o veículo para a faixa mais à esquerda ou mais à direita, dentro da respectiva mão de direção, quando for manobrar para um desses lados.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "198", "descricao": "Deixar de dar passagem pela esquerda, quando solicitado.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "202 I", "descricao": "Ultrapassar outro veículo pelo acostamento.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "202 II", "descricao": "Ultrapassar outro veículo em interseções e passagens de nível.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "206 I", "descricao": "Executar operação de retorno em locais proibidos pela sinalização.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "207", "descricao": "Executar operação de conversão à direita ou à esquerda em locais proibidos pela sinalização.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "214 I", "descricao": "Deixar de dar preferência de passagem a pedestre e a veículo não motorizado que se encontre na faixa a ele destinada.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "218 II", "descricao": "Transitar em velocidade superior à máxima permitida em mais de 20% até 50%.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "220", "descricao": "Deixar de reduzir a velocidade do veículo de forma compatível com a segurança do trânsito em diversas situações (aglomeração, passagem de ciclistas, etc.).", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "225", "descricao": "Deixar de sinalizar a via, de forma a prevenir os demais condutores e, à noite, não manter acesas as luzes externas ou omitir-se quanto a providências necessárias para tornar visível o local, quando tiver de remover o veículo da pista de rolamento ou permanecer no acostamento.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "230 V", "descricao": "Conduzir o veículo que não esteja registrado e devidamente licenciado.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "230 VI", "descricao": "Conduzir o veículo com qualquer uma das placas de identificação sem condições de legibilidade e visibilidade.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "233", "descricao": "Deixar de efetuar o registro de veículo no prazo de trinta dias.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "244 VIII", "descricao": "Conduzir motocicleta, motoneta e ciclomotor transportando carga incompatível com suas especificações.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  { "artigo": "248", "descricao": "Transportar em veículo destinado ao transporte de passageiros carga excedente em desacordo com o estabelecido no art. 109.", "grau": "Grave", "pontos": 5, "valor": 195.23 },
  
  // GRAVÍSSIMAS - 7 Pontos - R$ 293,47 (ou valor com fator multiplicador)
  { "artigo": "162 I", "descricao": "Dirigir veículo sem possuir CNH, PPD ou ACC.", "grau": "Gravíssima", "pontos": 7, "valor": 880.41 },
  { "artigo": "162 II", "descricao": "Dirigir veículo com CNH, PPD ou ACC cassada ou com suspensão do direito de dirigir.", "grau": "Gravíssima", "pontos": 7, "valor": 880.41 },
  { "artigo": "162 III", "descricao": "Dirigir veículo com CNH ou PPD de categoria diferente da do veículo que esteja conduzindo.", "grau": "Gravíssima", "pontos": 7, "valor": 586.94 },
  { "artigo": "162 V", "descricao": "Dirigir veículo com CNH vencida há mais de 30 dias.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "163", "descricao": "Entregar a direção do veículo a pessoa nas condições previstas no artigo 162.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "165", "descricao": "Dirigir sob a influência de álcool ou de qualquer outra substância psicoativa que determine dependência.", "grau": "Gravíssima", "pontos": 7, "valor": 2934.70 },
  { "artigo": "165-A", "descricao": "Recusar-se a ser submetido a teste, exame clínico, perícia ou outro procedimento que permita certificar influência de álcool ou outra substância psicoativa.", "grau": "Gravíssima", "pontos": 7, "valor": 2934.70 },
  { "artigo": "170", "descricao": "Dirigir ameaçando os pedestres que estejam atravessando a via pública, ou os demais veículos.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "173", "descricao": "Disputar corrida.", "grau": "Gravíssima", "pontos": 7, "valor": 2934.70 },
  { "artigo": "174", "descricao": "Promover, na via, competição, eventos organizados, exibição e demonstração de perícia em manobra de veículo, ou deles participar, como condutor, sem permissão da autoridade de trânsito.", "grau": "Gravíssima", "pontos": 7, "valor": 2934.70 },
  { "artigo": "175", "descricao": "Utilizar-se de veículo para demonstrar ou exibir manobra perigosa, mediante arrancada brusca, derrapagem ou frenagem com deslizamento ou arrastamento de pneus.", "grau": "Gravíssima", "pontos": 7, "valor": 2934.70 },
  { "artigo": "176 I", "descricao": "Deixar o condutor envolvido em acidente com vítima de prestar ou providenciar socorro.", "grau": "Gravíssima", "pontos": 7, "valor": 1467.35 },
  { "artigo": "181 V", "descricao": "Estacionar o veículo na pista de rolamento das estradas, das rodovias, das vias de trânsito rápido e das vias dotadas de acostamento.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "184 III", "descricao": "Transitar com o veículo na faixa ou via de trânsito exclusivo, regulamentada com circulação destinada aos veículos de transporte público coletivo de passageiros.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "186 I", "descricao": "Transitar pela contramão de direção em vias com duplo sentido de circulação, exceto para ultrapassar.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "189", "descricao": "Deixar de dar passagem aos veículos precedidos de batedores, de socorro de incêndio e salvamento, de polícia, de operação e fiscalização de trânsito e às ambulâncias, quando em serviço de urgência e devidamente identificados.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "191", "descricao": "Forçar passagem entre veículos que, transitando em sentidos opostos, estejam na iminência de passar um pelo outro ao realizar operação de ultrapassagem.", "grau": "Gravíssima", "pontos": 7, "valor": 2934.70 },
  { "artigo": "193", "descricao": "Transitar com o veículo em calçadas, passeios, passarelas, ciclovias, ciclofaixas, ilhas, refúgios, ajardinamentos, canteiros centrais e divisores de pista de rolamento, acostamentos, marcas de canalização, gramados e jardins públicos.", "grau": "Gravíssima", "pontos": 7, "valor": 880.41 },
  { "artigo": "203", "descricao": "Ultrapassar pela direita, salvo quando o veículo da frente estiver colocado na faixa apropriada e der sinal de que vai entrar à esquerda.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "203 V", "descricao": "Ultrapassar pela contramão outro veículo nas faixas de pedestre.", "grau": "Gravíssima", "pontos": 7, "valor": 1467.35 },
  { "artigo": "208", "descricao": "Avançar o sinal vermelho do semáforo ou o de parada obrigatória.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "210", "descricao": "Transpor, sem autorização, bloqueio viário policial.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "213 I", "descricao": "Deixar de parar o veículo sempre que a respectiva marcha for interceptada por agrupamento de pessoas, como préstitos, passeatas, desfiles e outros.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "214 IV", "descricao": "Deixar de dar preferência de passagem a pedestre e a veículo não motorizado que não haja concluído a travessia mesmo que ocorra sinal verde para o veículo.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "218 III", "descricao": "Transitar em velocidade superior à máxima permitida em mais de 50%.", "grau": "Gravíssima", "pontos": 7, "valor": 880.41 },
  { "artigo": "220 I", "descricao": "Deixar de reduzir a velocidade do veículo de forma compatível com a segurança do trânsito ao aproximar-se de passeatas, aglomerações, cortejos, préstitos e desfiles.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "230 I", "descricao": "Conduzir o veículo com o lacre, a inscrição do chassi, o selo, a placa ou qualquer outro elemento de identificação do veículo violado ou falsificado.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "230 II", "descricao": "Conduzir o veículo transportando passageiros em compartimento de carga, salvo por motivo de força maior, com permissão da autoridade competente e na forma estabelecida pelo CONTRAN.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "230 III", "descricao": "Conduzir o veículo com dispositivo anti-radar.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "231 VIII", "descricao": "Transitar com o veículo efetuando transporte remunerado de pessoas ou bens, quando não for licenciado para esse fim, salvo casos de força maior ou com permissão da autoridade competente.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "238", "descricao": "Recusar-se a entregar à autoridade de trânsito ou a seus agentes, mediante recibo, os documentos de habilitação, de registro, de licenciamento de veículo e outros exigidos por lei, para averiguação de sua autenticidade.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "239", "descricao": "Retirar do local veículo legalmente retido para regularização, sem permissão da autoridade competente ou de seus agentes.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "244 I", "descricao": "Conduzir motocicleta, motoneta e ciclomotor sem usar capacete de segurança ou vestuário de acordo com as normas e especificações aprovadas pelo CONTRAN.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "244 II", "descricao": "Conduzir motocicleta, motoneta e ciclomotor transportando passageiro sem o capacete de segurança ou fora do assento suplementar colocado atrás do condutor ou em carro lateral.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "244 III", "descricao": "Conduzir motocicleta, motoneta e ciclomotor fazendo malabarismo ou equilibrando-se apenas em uma roda.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "244 IV", "descricao": "Conduzir motocicleta, motoneta e ciclomotor com os faróis apagados.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "244 V", "descricao": "Conduzir motocicleta, motoneta e ciclomotor transportando criança menor de 10 anos de idade ou que não tenha, nas circunstâncias, condições de cuidar da própria segurança.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "252 Parágrafo Único", "descricao": "Dirigir o veículo segurando ou manuseando telefone celular.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "253", "descricao": "Bloquear a via com veículo.", "grau": "Gravíssima", "pontos": 7, "valor": 293.47 },
  { "artigo": "253-A", "descricao": "Usar qualquer veículo para, deliberadamente, interromper, restringir ou perturbar a circulação na via sem autorização.", "grau": "Gravíssima", "pontos": 7, "valor": 5869.40 }
]);